### ISSUE TITLE
搜索 URL：/store/search抛异常

### ISSUE THREAD

**Issue by shengming123** [lifengdi/search#2]
已存数据
{
    "_index": "store",
    "_type": "base",
    "_id": "1",
    "_version": 1,
    "_seq_no": 0,
    "_primary_term": 1,
    "found": true,
    "_source": {
        "id": "1",
        "storeId": "100",
        "storeName": "aaa",
        "updatedTime": "2022-01-12 15:16:17 ",
        "createdTime": "2022-01-12 15:16:17 "
    }
}

搜索
URL：/store/search
请求方式：POST
{
	"storeName": "aaa"
}
抛异常
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [baseInfo.createdTime] in order to sort on

**Comment by lifengdi** [comment]
[baseInfo.createdTime]  mapping中缺少baseInfo对象以及对象中的createdTime字段。或者改下默认排序方式也行

**Comment by shengming123** [comment]
谢谢，目前处理是添加createdTime字段，并且不能为空
